export const FLASH_ALERT_TYPE_ERROR = 'error';
export const FLASH_ALERT_TYPE_SUCCESS = 'success';
export const FLASH_ALERT_TYPE_INFO = 'info';

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const ADD_TO_CART = 'ADD_TO_CART';

export const OPENED_VIA_CART = 'OPENED_VIA_CART';
export const OPENED_VIA_HOME = 'OPENED_VIA_HOME';