export const FLASH_ALERT_TYPE_ERROR = 'error';
export const FLASH_ALERT_TYPE_SUCCESS = 'success';
export const FLASH_ALERT_TYPE_INFO = 'info';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const LOAD_MORE_PRODUCTS = "LOAD_MORE_PRODUCTS";
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_RTL = 'UPDATE_RTL';

export const OPENED_VIA_CART = 'OPENED_VIA_CART';
export const OPENED_VIA_HOME = 'OPENED_VIA_HOME';

export const PRODUCTS_PAGE_SIZE = 20;
export const TOTAL_PRODUCTS_COUNT = 100;